# Generated by Django 5.1.2 on 2024-11-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterField(
            model_name='movie',
            name='resim',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
